# Generated by Django 2.1 on 2019-02-18 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contest_time', models.DateTimeField()),
                ('contest_location', models.CharField(max_length=30)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('introduction', models.TextField()),
                ('rules', models.TextField()),
                ('reward', models.TextField()),
                ('type', models.IntegerField(choices=[(0, '个人赛'), (1, '组队赛')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('school_id', models.BigIntegerField()),
                ('qq_number', models.BigIntegerField()),
                ('faculty', models.CharField(max_length=20)),
                ('remark', models.IntegerField(choices=[(0, 'Accepted'), (1, 'Rejected'), (2, 'No Response'), (3, 'Waiting Judge'), (4, 'unRating'), (5, 'Skipped'), (6, 'Cancelled'), (7, 'Deleted')], default=3)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('remark', models.IntegerField(choices=[(0, 'Accepted'), (1, 'Rejected'), (2, 'No Response'), (3, 'Waiting Judge'), (4, 'unRating'), (5, 'Skipped'), (6, 'Cancelled'), (7, 'Deleted')], default=3)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.Contest')),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.Team'),
        ),
    ]
