# Generated by Django 2.1 on 2018-12-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('school_id', models.BigIntegerField()),
                ('qq_number', models.BigIntegerField()),
                ('faculty', models.CharField(max_length=20)),
            ],
        ),
    ]
