# Generated by Django 2.1 on 2019-02-19 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contest_location',
            field=models.CharField(max_length=30, verbose_name='比赛地点'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_time',
            field=models.DateTimeField(verbose_name='比赛时间'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='end_time',
            field=models.DateTimeField(verbose_name='报名结束时间'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='introduction',
            field=models.TextField(verbose_name='比赛介绍'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(max_length=30, verbose_name='比赛名称'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='reward',
            field=models.TextField(verbose_name='比赛奖励'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='rules',
            field=models.TextField(verbose_name='比赛规则'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_time',
            field=models.DateTimeField(verbose_name='报名开始时间'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='type',
            field=models.IntegerField(choices=[(0, '个人赛'), (1, '组队赛')], default=0, verbose_name='比赛类型'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.Contest', verbose_name='所属比赛'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='faculty',
            field=models.CharField(max_length=20, verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=10, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='qq_number',
            field=models.BigIntegerField(verbose_name='QQ号'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='remark',
            field=models.IntegerField(choices=[(0, 'Accepted'), (1, 'Rejected'), (2, 'No Response'), (3, 'Waiting Judge'), (4, 'UnRating'), (5, 'Skipped'), (6, 'Cancelled'), (7, 'Deleted')], default=3, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='school_id',
            field=models.BigIntegerField(verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.Team', verbose_name='所属队伍'),
        ),
        migrations.AlterField(
            model_name='team',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.Contest', verbose_name='所属比赛'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=30, verbose_name='队伍名称'),
        ),
    ]
