# Generated by Django 2.1 on 2018-12-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='remark',
            field=models.CharField(default='等待审核', max_length=10),
        ),
    ]
