# Generated by Django 2.1 on 2018-12-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_participant_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='remark',
            field=models.IntegerField(choices=[(0, 'Accepted'), (1, 'Rejected'), (2, 'No Response'), (3, 'Waiting')], default=3),
        ),
    ]
