# Generated by Django 2.1 on 2019-02-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20190221_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='problem_num',
        ),
        migrations.AddField(
            model_name='contest',
            name='contest_id',
            field=models.IntegerField(default=1, verbose_name='比赛ID'),
        ),
    ]
