# Generated by Django 2.1 on 2018-12-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_auto_20181207_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='remark',
            field=models.IntegerField(choices=[(0, 'Accepted'), (1, 'Rejected'), (2, 'No Response'), (3, 'Waiting Judge'), (4, 'Cancelled'), (5, 'Deleted')], default=3),
        ),
    ]
