# Generated by Django 2.1 on 2018-12-08 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_auto_20181207_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='remark',
            field=models.IntegerField(choices=[(0, 'Accepted'), (1, 'Rejected'), (2, 'No Response'), (3, 'Waiting Judge'), (4, 'unRating'), (5, 'Skipped'), (6, 'Cancelled'), (7, 'Deleted')], default=3),
        ),
    ]
