# Generated by Django 2.1 on 2019-04-08 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20190227_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('printed', models.BooleanField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.Contest')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.Team')),
            ],
        ),
    ]
