# Generated by Django 2.1 on 2019-04-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='pw',
            field=models.CharField(default='无效密码', max_length=16),
        ),
        migrations.AlterField(
            model_name='code',
            name='team',
            field=models.CharField(default='无效队伍', max_length=33),
        ),
    ]
