# Generated by Django 2.1 on 2019-04-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_auto_20190408_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='tim',
            field=models.CharField(default='', max_length=22),
        ),
        migrations.AddField(
            model_name='team',
            name='type',
            field=models.IntegerField(choices=[(0, 'normal'), (1, 'AllGirl'), (2, 'OtherSchool')], default=0, verbose_name='特殊队伍'),
        ),
    ]
